Console.WriteLine("Bem vindo ao Nem um pio!");
Console.WriteLine("");
Console.WriteLine("Qual a espécie do seu pet?");
string especie = Console.ReadLine()!;
Thread.Sleep(1000);
Console.WriteLine($"Qual a raça do seu {especie}?");
string raca = Console.ReadLine()!;
Thread.Sleep(1000);
Console.WriteLine($"Qual o nome do seu {especie}?");
string nome = Console.ReadLine()!;
Thread.Sleep(1000);
Console.WriteLine($"Qual a idade do seu {especie}?");
int idade = Convert.ToInt32(Console.ReadLine()!);
Thread.Sleep(1000);
Console.WriteLine($"Qual a cor do seu {especie}?");
string cor = Console.ReadLine()!;
Thread.Sleep(1000);
Console.WriteLine("Criando registro, aguarde um momento...");
Thread.Sleep(2000);
Console.WriteLine("");
Console.WriteLine("+=========================================================+");
Console.WriteLine("|                 Pet Hotel 'Nem um pio'                  |");
Console.WriteLine("+=========================================================+");
Console.WriteLine($"| Espécie ............{especie.ToUpper()} | Raça ...............{raca.ToUpper()} |");
Console.WriteLine("+=========================================================+");
Console.WriteLine($"| Atende pela alcunha de: .........................{nome.ToUpper()} |");
Console.WriteLine($"| Idade: {idade} ano(s) | Pelagem/Cor: ..................{cor.ToUpper()} |");
Console.WriteLine("+=========================================================+");
Console.WriteLine("");
